FROM docker.io/library/golang:1.22-alpine as builder

WORKDIR /app
COPY . .

RUN go build -o . ./cmd/client

FROM docker.io/library/alpine:3.20

COPY --from=builder /app/client /bin/client

ENTRYPOINT ["client"]
