FROM docker.io/library/golang:1.22-alpine as builder

WORKDIR /app
COPY . .

RUN go build -o . ./cmd/server

FROM docker.io/library/alpine:3.20
EXPOSE 9999

COPY --from=builder /app/server /bin/server

ENTRYPOINT ["server"]
