version: "3.9"

services:
  server:
    build:
      dockerfile: ./Dockerfile-Server
    restart: always
    ports:
      - '9999:9999'
    networks:
      - wow

  client-hard:
    build:
      dockerfile: ./Dockerfile-Client
    deploy:
      replicas: 1
    environment:
      - WOW_CLIENT_ID=2b1d273c-aca3-4b79-b44a-6221cf60c6af
      - WOW_CLIENT_HOST=server
    restart: always
    networks:
      - wow

  client-easy:
    build:
      dockerfile: ./Dockerfile-Client
    deploy:
      replicas: 1
    environment:
      - WOW_CLIENT_HOST=server
    restart: always
    networks:
      - wow

networks:
  wow:
